### ISSUE TITLE
hello, how to display this picture?

### ISSUE THREAD

**Issue by Wusir2018** [BHafsa/image-nilm#2]
hello, 
how to display this picture? Could you tell me?
Thank you very much!
![imaging_techiques](https://user-images.githubusercontent.com/51500032/109486578-061ef880-7abe-11eb-9e42-d955da8fd592.PNG)

**Comment by BHafsa** [comment]
hello, 
I added a notebook that will allow you to have each image separately.

**Comment by Wusir2018** [comment]
@BHafsa 
Hey,thank you very much!
Best wishes! :)
